apiVersion: apps/v1
kind: Deployment
metadata:
  name: Bank-app-deployment
  labels:
    app: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp 
    spec:
      containers:
      - name: nodeserver
        image: juveria1340/project_4:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: Bank-app-service
spec:
  selector:
    app: bankapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
